# Generated by Django 2.0.6 on 2018-06-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_articleview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('contenets', models.TextField(max_length=100)),
                ('category_id', models.IntegerField()),
                ('category_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'view_article',
                'managed': False,
            },
        ),
    ]
